tag_and_descriptions_list:
  default: >-
    [
      {"tag_name": "tag-layouts", "Tag Layouts Help >>": "<table>
<thead>
<tr>
<th>TAG</th>
<th>HIDES/MODIFIES ELEMENT(S)</th>
</tr>
</thead>
<tbody>
<tr>
<td>hide-all-but-topic-body</td>
<td>[hides and modifies all of the below at once]</td>
</tr>
<tr>
<td>hide-header</td>
<td>.d-header</td>
</tr>
<tr>
<td>hide-sidebar</td>
<td>.sidebar-wrapper</td>
</tr>
<tr>
<td>hide-topic-status</td>
<td>.title-wrapper .topic-statuses</td>
</tr>
<tr>
<td>hide-title</td>
<td>#topic-title</td>
</tr>
<tr>
<td>hide-avatar</td>
<td>.topic-avatar</td>
</tr>
<tr>
<td>hide-author</td>
<td>.topic-meta-data.names</td>
</tr>
<tr>
<td>hide-edits</td>
<td>div.post-info.edits</td>
</tr>
<tr>
<td>hide-post-date</td>
<td>div.post-info.post-date</td>
</tr>
<tr>
<td>hide-read-state</td>
<td>.topic-body .read-state</td>
</tr>
<tr>
<td>hide-category</td>
<td>.topic-category</td>
</tr>
<tr>
<td>hide-all-meta-data</td>
<td>.topic-meta-data</td>
</tr>
<tr>
<td>hide-timeline</td>
<td>.topic-navigation.with-timeline</td>
</tr>
<tr>
<td>hide-mobile-topic-progress</td>
<td>div#topic-progress</td>
</tr>
<tr>
<td>hide-topic-footer-buttons</td>
<td>#topic-footer-buttons</td>
</tr>
<tr>
<td>hide-topic-map</td>
<td>div.topic-map</td>
</tr>
<tr>
<td>hide-more-topics</td>
<td>div.more-topics__container</td>
</tr>
<tr>
<td>hide-more-content</td>
<td>.more-content-wrapper</td>
</tr>
<tr>
<td>hide-suggested-topics-message</td>
<td>.suggested-topics-message</td>
</tr>
<tr>
<td>hide-post-links</td>
<td>.post-links-container</td>
</tr>
<tr>
<td>hide-main-side-margins</td>
<td>[adjusts columns and other widths]</td>
</tr>
<tr>
<td>hide-post-menu-area</td>
<td>.post-menu-area</td>
</tr>
<tr>
<td>hide-reactions</td>
<td>.discourse-reactions-actions</td>
</tr>
<tr>
<td>hide-copy-link</td>
<td>button.widget-button.btn-flat.post-action-menu__copy-link.no-text.btn-icon</td>
</tr>
<tr>
<td>hide-like-button</td>
<td>button.widget-button.btn-flat.button-count.like-count.highlight-action.regular-likes.btn-icon-text</td>
</tr>
<tr>
<td>hide-flag-button</td>
<td>button.widget-button.btn-flat.create-flag.no-text.btn-icon</td>
</tr>
<tr>
<td>hide-bookmark-button</td>
<td>button.widget-button.btn-flat.bookmark.with-reminder.no-text.btn-icon</td>
</tr>
<tr>
<td>hide-reply-button</td>
<td>button.widget-button.btn-flat.reply.create.fade-out.btn-icon-text</td>
</tr>
<tr>
<td>hide-signup-cta</td>
<td>.signup-cta</td>
</tr>
<tr>
<td>hide-main-padding</td>
<td>[removes all padding from <em>#main-outlet</em>]</td>
</tr>
<tr>
<td>hide-topic-border-top</td>
<td>[removes <em>border-top</em> from <em>.topic-body</em>]</td>
</tr>
<tr>
<td>hide-topic-border-bottom</td>
<td>[removes <em>border-top</em> from <em>.topic-status-info, .topic-timer-info</em>]</td>
</tr>
<tr>
<td>hide-small-action-posts</td>
<td>.small-action.onscreen-post</td>
</tr>
<tr>
<td>hide-</td>
<td>[MORE??]</td>
</tr>
</tbody>
</table>

  
<table>
<thead>
<tr>
<th>TAG</th>
<th>HIDES/MODIFIES ELEMENT(S) - THESE ITEMS ARE <em>NOT</em> INCLUDED WHEN THE hide-all-but-topic-body TAG IS APPLIED</th>
</tr>
</thead>
<tbody>
<tr>
<td>hide-topic-bg-color</td>
<td>[sets <em>background-color: transparent</em> on <em>#main-outlet</em>]</td>
</tr>
<tr>
<td>hide-</td>
<td>[MORE??]</td>
</tr>
</tbody>
</table>

  
<table>
<thead>
<tr>
<th>TAG1</th>
<th>TAG2</th>
<th>HIDES ALL BUT SHOWS SOME THING(S)</th>
</tr>
</thead>
<tbody>
<tr>
<td>hide-all-but-topic-body</td>
<td>show-timeline</td>
<td>[Hides Everything But TOC/Topic Timeline]</td>
</tr>
</tbody>
</table>

  
<table>
<thead>
<tr>
<th>Theme/Component/Plugin</th>
<th>TAG</th>
<th>HIDES/MODIFIES ELEMENT(S) - THESE ITEMS ARE SPECIFIC TO THEMES, THEME COMPONENTS AND PLUGINS</th>
</tr>
</thead>
<tbody>
<tr>
<td>Elegant Theme</td>
<td>hide-topic-body-box-shadow</td>
<td>[removes <em>box-shadow</em> from <em>.topic-body</em> in the Elegant Theme]</td>
</tr>
<tr>
<td>Header Submenus</td>
<td>hide-header-submenus</td>
<td>[removes Header Submenus Theme Component]</td>
</tr>
<tr>
<td>Discourse Drawer</td>
<td>hide-drawer</td>
<td>[removes Discourse Drawer Theme Component]</td>
</tr>
</tbody>
</table>", "hide_for_OP": false, "hide_for_replyer": false}
    ]
  json_schema: |
    {
      "type": "array",
      "format": "table",
      "items": {
        "type": "object",
        "properties": {
          "tag_name": { "type": "string" },
          "short_description": { "type": "string" },
          "long_description": { "type": "string" },
          "hide_for_OP": {"type": "boolean", "default": false},
          "hide_for_replyer": {"type": "boolean", "default": false}
        }
      }
    }
  description:
    zh_CN: |
      配置不同的Tag显示什么。支持HTML。
      tag_name为您需要展现的名称。hide_for_OP为是否为楼主展现说明。
      hide_for_replyer为对已经回复过的人隐藏。
    en: |
      Configure what to display for different Tags. HTML is supported.
      `hide_for_OP` is whether to hide tips for the original poster.
      `hide_for_replyer` hides from those who have already replied.
show_modal_instead_of_summary:
  default: false
  description: 
    zh_CN: 显示弹窗而非显示文本。适合需要写很长的文本，编辑框不够放时。
    en: Show modal rather than details box. Suitable for writing very long text, when the edit box is not enough.
