tag_and_descriptions_list:
  default: >-
    [
      {"tag_name": "tag-layouts", "short_description": "Tag Layouts Help >>", "long_description": "<iframe src=\"https://denvergeeks.github.io/discourse-tag-layouts/\" style=\"height: 15em; width: 100%\"></iframe>", "hide_for_OP": false, "hide_for_replyer": false}
    ]
  json_schema: |
    {
      "type": "array",
      "format": "table",
      "items": {
        "type": "object",
        "properties": {
          "tag_name": { "type": "string" },
          "short_description": { "type": "string" },
          "long_description": { "type": "string" },
          "hide_for_OP": {"type": "boolean", "default": false},
          "hide_for_replyer": {"type": "boolean", "default": false}
        }
      }
    }
  description:
    zh_CN: |
      配置不同的Tag显示什么。支持HTML。
      tag_name为您需要展现的名称。hide_for_OP为是否为楼主展现说明。
      hide_for_replyer为对已经回复过的人隐藏。
    en: |
      Configure what to display for different Tags. HTML is supported.
      `hide_for_OP` is whether to hide tips for the original poster.
      `hide_for_replyer` hides from those who have already replied.
show_modal_instead_of_summary:
  default: false
  description: 
    zh_CN: 显示弹窗而非显示文本。适合需要写很长的文本，编辑框不够放时。
    en: (MODAL NOT CURRENTLY WORKING) Show modal rather than details box. Suitable for writing very long text, when the edit box is not enough.
