tag_and_descriptions_list:
  default: >-
    [
      {"tag_name": "tag-layouts", "Tag Layouts Help >>": "# Hide Elements Using Tags

## Tag Layouts

| TAG | HIDES-MODIFIES ELEMENT                                                                         |
| ------------------------------- | -------------------------------------------------------------------------------------------------- |
| `hide-all-but-topic-body`       | \[hides and modifies all of the below at once]                                                     |
| `hide-header`                   | .d-header                                                                                          |
| `hide-sidebar`                  | .sidebar-wrapper                                                                                   |
| `hide-topic-status`             | .title-wrapper .topic-statuses                                                                     |
| `hide-title`                    | #topic-title                                                                                       |
| `hide-avatar`                   | .topic-avatar                                                                                      |
| `hide-author`                   | .topic-meta-data.names                                                                             |
| `hide-edits`                    | div.post-info.edits                                                                                |
| `hide-post-date`                | div.post-info.post-date                                                                            |
| `hide-read-state`               | .topic-body .read-state                                                                            |
| `hide-category`                 | .topic-category                                                                                    |
| `hide-all-meta-data`            | .topic-meta-data                                                                                   |
| `hide-timeline`                 | .topic-navigation.with-timeline                                                                    |
| `hide-mobile-topic-progress`    | div#topic-progress                                                                                 |
| `hide-topic-footer-buttons`     | #topic-footer-buttons                                                                              |
| `hide-topic-map`                | div.topic-map                                                                                      |
| `hide-more-topics`              | div.more-topics\_\_container                                                                       |
| `hide-more-content`             | .more-content-wrapper                                                                              |
| `hide-suggested-topics-message` | .suggested-topics-message                                                                          |
| `hide-post-links`               | .post-links-container                                                                              |
| `hide-main-side-margins`        | \[adjusts columns and other widths]                                                                |
| `hide-post-menu-area`           | .post-menu-area                                                                                    |
| `hide-reactions`                | .discourse-reactions-actions                                                                       |
| `hide-copy-link`                | button.widget-button.btn-flat.post-action-menu\_\_copy-link.no-text.btn-icon                       |
| `hide-like-button`              | button.widget-button.btn-flat.button-count.like-count.highlight-action.regular-likes.btn-icon-text |
| `hide-flag-button`              | button.widget-button.btn-flat.create-flag.no-text.btn-icon                                         |
| `hide-bookmark-button`          | button.widget-button.btn-flat.bookmark.with-reminder.no-text.btn-icon                              |
| `hide-reply-button`             | button.widget-button.btn-flat.reply.create.fade-out.btn-icon-text                                  |
| `hide-signup-cta`               | .signup-cta                                                                                        |
| `hide-main-padding`             | \[removes all padding from _#main-outlet_]                                                         |
| `hide-topic-border-top`         | \[removes _border-top_ from _.topic-body_]                                                         |
| `hide-topic-border-bottom`      | \[removes _border-top_ from _.topic-status-info, .topic-timer-info_]                               |
| `hide-small-action-posts`       | .small-action.onscreen-post                                                                        |

| TAG                   | HIDES-MODIFIES - OTHER                         |
| --------------------- | --------------------------------------------------------- |
| `hide-topic-bg-color` | \[sets _background-color: transparent_ on _#main-outlet_] |

#### Tag Combinations to Hide All But Show Some Thing(s)...

| TAG1                      | TAG2            | SHOWS-MODIFIES ELEMENT                  |
| ------------------------- | --------------- | ------------------------------------------ |
| `hide-all-but-topic-body` | `show-timeline` | \[Hides Everything But TOC/Topic Timeline] |
| `?`                       | `?`             | \[?]                                       |
| `?`                       | `?`             | \[?]                                       |

#### Tags Specific to a Theme Component or Plugin...

| Theme/Component/Plugin | TAG                          | HIDES/MODIFIES ELEMENT(S)                                       |
| ---------------------- | ---------------------------- | --------------------------------------------------------------- |
| Elegant Theme          | `hide-topic-body-box-shadow` | \[removes _box-shadow_ from _.topic-body_ in the Elegant Theme] |
| Header Submenus        | `hide-header-submenus`       | \[removes Header Submenus Theme Component]                      |
| Discourse Drawer       | `hide-drawer`                | \[removes Discourse Drawer Theme Component]                     |

Background: [Create custom layouts for individual Topic Posts in Discourse](https://meta.discourse.org/t/page-publishing/151971/145)
", "hide_for_OP": false, "hide_for_replyer": false}
    ]
  json_schema: |
    {
      "type": "array",
      "format": "table",
      "items": {
        "type": "object",
        "properties": {
          "tag_name": { "type": "string" },
          "short_description": { "type": "string" },
          "long_description": { "type": "string" },
          "hide_for_OP": {"type": "boolean", "default": false},
          "hide_for_replyer": {"type": "boolean", "default": false}
        }
      }
    }
  description:
    zh_CN: |
      配置不同的Tag显示什么。支持HTML。
      tag_name为您需要展现的名称。hide_for_OP为是否为楼主展现说明。
      hide_for_replyer为对已经回复过的人隐藏。
    en: |
      Configure what to display for different Tags. HTML is supported.
      `hide_for_OP` is whether to hide tips for the original poster.
      `hide_for_replyer` hides from those who have already replied.
show_modal_instead_of_summary:
  default: false
  description: 
    zh_CN: 显示弹窗而非显示文本。适合需要写很长的文本，编辑框不够放时。
    en: Show modal rather than details box. Suitable for writing very long text, when the edit box is not enough.
